export enum ErrorCode {
    FAILED_VALIDATION = 'FAILED_VALIDATION',
    FORBIDDEN = 'FORBIDDEN',
    INVALID_TOKEN = 'INVALID_TOKEN',
    TOKEN_EXPIRED = 'TOKEN_EXPIRED',
    INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
    INVALID_IP = 'INVALID_IP',
    INVALID_OTP = 'INVALID_OTP',
    INVALID_PAYLOAD = 'INVALID_PAYLOAD',
    INVALID_QUERY = 'INVALID_QUERY',
    UNSUPPORTED_MEDIATYPE = 'UNSUPPORTED_MEDIA_TYPE',
    RECORD_NOTUNIQUE = 'RECORD_NOT_UNIQUE',
    REQUESTS_EXCEEDED = 'REQUESTS_EXCEEDED',
    ROUTE_NOTFOUND = 'ROUTE_NOT_FOUND',
    SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',
    UNPROCESSABLE_ENTITY = 'UNPROCESSABLE_ENTITY'
}

export interface DirectusError extends Error {
    message: string;
    extensions: { code: string };
}
